services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.web.dev
  #   container_name: web_dev
  #   volumes:
  #     - ./apps/web:/workspace/apps/web
  #     - /workspace/apps/web/node_modules
  #   working_dir: /workspace/apps/web
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NODE_ENV=development
  #   command: pnpm dev

  # graphql:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.graphql.dev
  #   container_name: graphql_dev
  #   volumes:
  #     - ./apps/graphql:/workspace/apps/graphql
  #     - /workspace/apps/graphql/node_modules
  #   working_dir: /workspace/apps/graphql
  #   ports:
  #     - '4000:4000'
  #   environment:
  #     - NODE_ENV=development
  #   command: pnpm start:dev

  postgis:
    image: postgis/postgis:latest
    container_name: safe-driving-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sd_usr
      POSTGRES_PASSWORD: sd_pwd
      POSTGRES_DB: sd_db
    ports:
      - "5435:5432"
    volumes:
      - safe_driving_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sd_usr -d sd_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@safedriving.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgis

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - LT_DEBUG=true
      - LT_LOAD_ONLY=fr,en
      - LT_DISABLE_WEB_UI=false
      - ARGOS_DEBUG=1
      - ARGOS_TRANSLATE_DATA_DIR=/app/data  # Répertoire personnalisé
    volumes:
      - libretranslate_data:/app/data  # Montage vers le répertoire personnalisé
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  # LocalStack with S3, Elasticsearch, SES (e-mail)
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"   # Edge port for all services
      # Optional legacy ports (not required when using edge)
      - "4510-4559:4510-4559"   # Legacy S3 port,Legacy Elasticsearch port, Legacy SES port
    environment:
      - SERVICES=s3,es,ses       # Enable S3, Elasticsearch, SES services
      - DEBUG=1                  # Enable debug logs
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      # Optional: specify Elasticsearch version
      - DEFAULT_REGION=us-east-1
      - LOCALSTACK_DISABLE_TMP_FOLDER_CLEAR=1
    volumes:
      - "./localstack_data:/var/lib/localstack" # Mounts the local directory to the container
      - "/var/run/docker.sock:/var/run/docker.sock" # Mounts the docker socket

      
volumes:
  pgadmin_data:
  minio_data:
  safe_driving_data:
  libretranslate_data:
  localstack_data:
    driver: local
