services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.web.dev
  #   container_name: web_dev
  #   volumes:
  #     - ./apps/web:/workspace/apps/web
  #     - /workspace/apps/web/node_modules
  #   working_dir: /workspace/apps/web
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NODE_ENV=development
  #   command: pnpm dev

  # graphql:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.graphql.dev
  #   container_name: graphql_dev
  #   volumes:
  #     - ./apps/graphql:/workspace/apps/graphql
  #     - /workspace/apps/graphql/node_modules
  #   working_dir: /workspace/apps/graphql
  #   ports:
  #     - '4000:4000'
  #   environment:
  #     - NODE_ENV=development
  #   command: pnpm start:dev

  postgis:
    image: postgis/postgis:latest
    container_name: safe-driving-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sd_usr
      POSTGRES_PASSWORD: sd_pwd
      POSTGRES_DB: sd_db
    ports:
      - "5432:5432"
    volumes:
      - safe_driving_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sd_usr -d sd_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@safedriving.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgis

  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    restart: unless-stopped
    ports:
      - "5000:5000"

  safe-driving-minio-db:
    image: minio/minio:latest
    container_name: safe-driving-minio-server
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: sd_minio_usr
      MINIO_ROOT_PASSWORD: sd_minio_pwd
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio_data:/data

      
volumes:
  pgadmin_data:
  minio_data:
  safe_driving_data:
