# Le fichier .osm.pbf à télécharger depuis Geofabrik via ce lien: https://download.geofabrik.de/africa/madagascar.html
# Le transférer dans le dossier ors-data/pbf (à créer si besoin).

services:
  ors:
    image: openrouteservice/openrouteservice:latest
    container_name: ors
    ports:
      - "8085:8082"
    volumes:
      - ./ors-data/graphs:/home/ors/graphs
      - ./ors-data/elevation_cache:/home/ors/elevation_cache
      - ./ors-data/configs:/home/ors/config
      - ./ors-data/configs/ors-config.yml:/home/ors/config/ors-config.yml
      - ./ors-data/pbf/madagascar-latest.osm.pbf:/home/ors/files/madagascar-latest.osm.pbf
    restart: unless-stopped
