name: safe_driving
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # Paquet pour la localisation et l'internationalisation
  flutter_localizations:
    sdk: flutter
  # Paquet pour les outils d'internationalisation
  intl: ^0.20.2
  #GOOGLE NAVBAR
  google_nav_bar: ^5.0.7

  graphql_flutter: ^5.2.0
  provider: ^6.1.5
  flutter_dotenv: ^5.2.1
  gql_build: ^0.11.0+1
  percent_indicator: ^4.2.5
  smooth_page_indicator: ^1.2.1
  flutter_markdown: ^0.7.7+1

  # for photos
  flutter_svg: ^2.2.0
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  camera: ^0.11.2
  universal_html: ^2.2.4
  permission_handler: ^12.0.1
  camera_web: ^0.3.5
  #for gps
  geolocator: ^14.0.2
  shared_preferences: ^2.5.3

  # for file storage
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_screenutil: ^5.9.3
  
  # for json serialization
  json_annotation: ^4.9.0
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - lib/resources/assets/img/social/
    - lib/resources/assets/logo/
    - lib/resources/assets/home/icons/
  fonts:
    - family: Inder
      fonts:
        - asset: lib/resources/assets/fonts/Inder/Inder-Regular.ttf
          weight: 700
