name: safe_driving
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_nav_bar: ^5.0.7
  #socket
  web_socket_channel: ^3.0.1
  emoji_picker_flutter: ^1.6.3

  graphql_flutter: ^5.2.0
  provider: ^6.1.5
  flutter_dotenv: ^5.2.1
  gql_build: ^0.11.0+1
  percent_indicator: ^4.2.5
  smooth_page_indicator: ^1.2.1
  flutter_markdown: ^0.7.7+1

  flutter_svg: ^2.2.0
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  camera: ^0.11.2
  universal_html: ^2.2.4
  permission_handler: ^12.0.1
  camera_web: ^0.3.5
  geolocator: ^14.0.2
  shared_preferences: ^2.5.3

  path_provider: ^2.1.5
  file_picker: ^6.1.1
  url_launcher: ^6.2.2
  open_file: ^3.2.1
  path: ^1.9.1
  flutter_screenutil: ^5.9.3
  http: ^1.2.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  socket_io_client: ^2.0.3

  json_annotation: ^4.9.0
  confetti: ^0.8.0
  flutter_map_marker_cluster: ^1.4.0
  cached_network_image: ^3.3.1
  quiver: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - .env.web
    - lib/resources/assets/img/social/
    - lib/resources/assets/logo/
    - lib/resources/assets/home/icons/
  fonts:
    - family: Inder
      fonts:
        - asset: lib/resources/assets/fonts/Inder/Inder-Regular.ttf
          weight: 700
